<?php

/**
 * ApplicationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ApplicationTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ApplicationTable
     */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Application');
  }
    
  const
    STATUS_ACTIVE       = 1,
    STATUS_INACTIVE     = 0;
    
  protected static
    $status                = array
                             (
                               self::STATUS_ACTIVE     => 'Si'  ,
                               self::STATUS_INACTIVE   => 'No',
                             );
                             
  public function getStatuss()
  {
    return self::$status;
  }	
  
  
  public function getNewRank()
  {
    $q = $this->createQuery('a')
  	      ->addSelect('MAX(rank)');
  	           
    $dato = $q->execute()->getFirst()->toArray();
    return $dato['MAX']+1;
  	 
  }

  
  public function getPathDir()
  {
    return sfConfig::get('app_application_images_dir');
  }
  
  public function getImagePath()
  {
    return sfConfig::get('app_application_images_path');
  }
  
  public function findApplications()
  {
    return $this->findQueryApplications()->execute();
  }
  
    public function findQueryApplications()
  {
    $q = $this->createQuery('a')
              ->addWhere('a.active = 1')
              ->orderBy('rank asc');
    
    return $q;
  }
}