homepage:
  url:             /
  param:           { module: Home, action: index}

nosotros:
  url:             /:sf_culture/nosotros
  param:           { module: Home, action: nosotros}

servicios:
  url:             /:sf_culture/servicios
  param:           { module: Home, action: servicios}

proyectos:
  url:             /:sf_culture/proyectos/:slug
  param:           { module: Home, action: proyectos, slug: ''}
  requirements:    { slug: \w+ }

contactenos:
  url:             /:sf_culture/contactenos
  param:           { module: Home, action: contactenos}

sitemap:
  url:             /:sf_culture/sitemap
  param:           { module: Home, action: sitemap}

image:
  url:             /image
  param:           { module: Home, action: image}
  
change_language:
  url:             /change/language
  param:           { module: Home, action: changeLanguage }
  
default:
  url:             /:module/:action/*
