default:
  http_metas:
    content-type: text/html
    Expires: Mon, 26 Jul 1997 05:00:00 GMT

  metas:
    title:        DATA Solutions
    description:  Data solutions es una empresa dedicado al desarrollo de aplicaciones WEB 2.0.
    keywords:     DATA Solutions, data, solutions, solucion, datos, soluciones, web, aplicacion, aplicaciones, peru, symfony, doctrine, oracle,php
    language:     en,es
    content-language: en,es
    robots:       index, follow

  stylesheets:
    - frontend/reset.css:               { media: all }
    - frontend/style.css:               { media: all }
    
  javascripts:
    - jquery/jquery-1.4.2.min.js
    - frontend/cufon-yui.js
    - frontend/Humanst521_BT_400.font.js
    - frontend/Humanst521_Lt_BT_400.font.js
    - frontend/jquery.roundabout.min.js
    - frontend/roundabout_shapes.js
    - jquery/jquery.scrollTo.min.js
    - frontend/gallery_init.js
    - frontend/cufon-replace.js
    
    
  has_layout:     true
  layout:         layout
