News:
  tableName:                           t_news
  actAs:
    Timestampable:
    SluggableExt:                      { fields: [ title ] }
  columns:
    id:                                { type: integer  , length: 20 , primary: true    , autoincrement: true                                                  }
    title:                             { type: string   , length: 200                   , notnull: true                                                        } 
    description:                       { type: string   , length: 5000                  , notnull: true                                                        }
    active:                            { type: string   , length: 1  , fixed: true      , notnull: true , default: 0                                           } 
  indexes:
    i_title:                           { fields: [ title ]                                                                                                     }
    i_active:                          { fields: [ active ]                                                                                                    }
  options:
    symfony:                           { filter: false, form: true }
    boolean_columns:                   [ active ]
